ehrs/urls.py
from django.urls import path

from . import views

app_name = 'ehrs'
urlpatterns = [
    # ex: /ehrs/
    path('', views.index, name='index'),    # path(regex, function inside views file, name associated with function)
    # ex: /ehrs/main/
    path('main/', views.main, name='main'),
    # ex: /ehrs/main/ehrinfo/123/
    path('main/ehrinfo/<uid>', views.ehrinfo, name='ehrinfo'),
    path('main/ehrcreate/', views.ehrcreate, name='ehrcreate'),
    path('main/ehrcreate/createsuccess/', views.createsuccess, name='createsuccess'),
    path('main/compcreate/', views.compcreate, name='compcreate'),
    path('main/compsuccess/', views.compsuccess, name='compsuccess'),
    path('main/ehrinfo/<uid>/compdisplay/<index>', views.compdisplay, name='compdisplay')
]

webclinic/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('ehrs/', include('ehrs.urls')),    # use include function to extend urls of polls app over mysite.
    path('admin/', admin.site.urls),
]

ehrs/models.py
from django.db import models

# Create your models here.
class Ehr(models.Model):
    ehruid = models.CharField(max_length=100)
    name = models.CharField(max_length=100)

ehrs/views.py
from django.shortcuts import render
from django.http import HttpResponse
import requests as r
import random, string, datetime
from .loginform import loginform, newehr, templateselect, vitalcomp, cancercomp
import json, os
import re
import numpy as np
import csv
from sklearn import svm
from sklearn.neural_network import MLPClassifier

token = ""
links = []
username = "not logged in"
template = ""
ehruid = ""
namelist = []
formlist = []


def index(request):
    return HttpResponse(render(request, 'ehrs/index.html'))


def main(request):
    global token, links, username

    if request.method == 'POST':
        form = loginform(request.POST)
        if form.is_valid():
            username = str(form.cleaned_data['user'])
            password = str(form.cleaned_data['password'])
            organization = str(form.cleaned_data['organization'])

            parameters = {"username": username,
                          "password": password,
                          "organization": organization
                          }
            response = r.post('http://localhost:8090/ehr/api/v1/login', params=parameters)

            token = "Bearer " + str(response.json()['token'])
            # fetching user info
            user_resp = r.get('http://localhost:8090/ehr/api/v1/users/' + username, params={"format": "json"},
                              headers={"Authorization": token})
            user_info = user_resp.text.replace(",", "\n").replace("{", "").replace("[", "").replace(":",
                                                                                                    " - ").replace(
                "}", "\n").replace("]", "\n").replace("\"", "")

            # fetching ehr list
            ehrlist_resp = r.get('http://localhost:8090/ehr/api/v1/ehrs', params={"format": "json"},
                                 headers={"Authorization": token})
            ehrlist_json = json.loads(ehrlist_resp.text)
            json_filtered = str(ehrlist_json["ehrs"])
            ehr_list = []
            for i in range(0, len(ehrlist_json["ehrs"])):
                links.append(str(ehrlist_json["ehrs"][i]["uid"]))
                ehr_list.append(
                    str(ehrlist_json["ehrs"][i]["uid"]) + "  ------  " + str(ehrlist_json["ehrs"][i]["dateCreated"]))

            zipped = zip(links, ehr_list)
            return HttpResponse(render(request, 'ehrs/main.html', {"user_info": user_info, "zipped": zipped}))

    if len(token) != 0:
        user_resp = r.get('http://localhost:8090/ehr/api/v1/users/' + username, params={"format": "json"},
                          headers={"Authorization": token})
        user_info = user_resp.text.replace(",", "\n").replace("{", "").replace("[", "").replace(":",
                                                                                                " - ").replace(
            "}", "\n").replace("]", "\n").replace("\"", "")

        # fetching ehr list
        ehrlist_resp = r.get('http://localhost:8090/ehr/api/v1/ehrs', params={"format": "json"},
                             headers={"Authorization": token})
        ehrlist_json = json.loads(ehrlist_resp.text)
        json_filtered = str(ehrlist_json["ehrs"])
        ehr_list = []
        for i in range(0, len(ehrlist_json["ehrs"])):
            links.append(str(ehrlist_json["ehrs"][i]["uid"]))
            ehr_list.append(
                str(ehrlist_json["ehrs"][i]["uid"]) + "  ------  " + str(ehrlist_json["ehrs"][i]["dateCreated"]))

        zipped = zip(links, ehr_list)
        return HttpResponse(render(request, 'ehrs/main.html', {"user_info": user_info, "zipped": zipped}))

    else:
        return HttpResponse("not logged in.")


def ehrinfo(request, uid):
    global ehruid, template
    ehruid = str(request.get_full_path().replace("/ehrs/main/ehrinfo/", ""))

    ehrinfo_resp = r.get('http://localhost:8090/ehr/api/v1/ehrs/ehrUid/' + ehruid, params={"format": "json"},
                         headers={"Authorization": token}).text.replace(",", "\n").replace("{", "").replace("[",
                                                                                                            "").replace(
        ":",
        " - ").replace(
        "}", "\n").replace("]", "\n").replace("\"", "")

    z = json.load(open("C:\\Users\\DELL\\Desktop\\webclinic\\ehrs\\data.json"))

    composition_links = []
    composition_details = []
    indexlist = []
    try:
        for j in range(len(z[ehruid]["compositions"])):
            composition_links.append("Compostion Uid: " + z[ehruid]["compositions"][j]["composition_uid"])
            composition_details.append("Date Created: " + z[ehruid]["compositions"][j]["date_created"] + "\n" + "            Template Type: " + z[ehruid]["compositions"][j]["template_name"])
            indexlist.append(str(j))


    except:
        print("xyz")


    zipped = zip(indexlist, composition_links, composition_details)

    return HttpResponse(render(request, 'ehrs/ehrinfo.html', {"ehrinfo_resp": ehrinfo_resp, "zipped": zipped, "uid": ehruid}))


def ehrcreate(request):
    return HttpResponse(render(request, "ehrs/ehrcreate.html"))


def createsuccess(request):
    if request.method == 'POST':
        form = newehr(request.POST)
        print("a")
        if form.is_valid():
            print("b")
            ehruid = str(form.cleaned_data["ehruid"])
            subuid = str(form.cleaned_data["subuid"])
            if len(ehruid) == 0:
                print("c")
                ehruid = ''.join(
                    [random.choice(string.ascii_letters + string.digits) for n in range(36)])
                response = r.post("http://localhost:8090/ehr/api/v1/ehrs",
                                  params={"format": "json", "uid": ehruid, "subjectUid": subuid}, headers={"Authorization": token})
                print("response: " + response.text)

                z = json.load(open("C:\\Users\\DELL\\Desktop\\webclinic\\ehrs\\data.json"))
                z[ehruid] = {"compositions": []}
                json.dump(z, open("C:\\Users\\DELL\\Desktop\\webclinic\\ehrs\\data.json", 'w'))
            else:
                print("d")
                response = r.post("http://localhost:8090/ehr/api/v1/ehrs",
                                  params={"format": "json", "uid": ehruid, "subjectUid": subuid},
                                  headers={"Authorization": token})
                print("response: " + response.text)
                z = json.load(open("C:\\Users\\DELL\\Desktop\\webclinic\\ehrs\\data.json"))
                z[ehruid] = {"compositions": []}
                json.dump(z, open("C:\\Users\\DELL\\Desktop\\webclinic\\ehrs\\data.json", 'w'))
    print("e")
    return HttpResponse(render(request, 'ehrs/createsuccess.html'))


def compcreate(request):
    global template, ehruid, namelist, formlist
    if request.method == 'GET':
        form = templateselect(request.GET)
        print("a")
        if form.is_valid():
            print("b")
            template = str(form.cleaned_data["template"])
            if template == "Vital Signs":
                formlist = ["Age", "Sex", "Chest Pain Type (1-4)", "Resting blood pressure (mm Hg)",
                            "serum cholestoral (mg/dl)", "fasting blood sugar>120 mg/dl (1 = true; 0 = false)",
                            "resting electrocardiographic results: (class 0-2): ",
                            "maximum heart rate achieved", "exercise induced angina (1 = yes; 0 = no)",
                            "ST depression induced by exercise relative to rest",
                            "the slope of the peak exercise ST segment: (class 1-3)",
                            "number of major vessels (0-3)",
                            " thal: 3 = normal, 6 = fixed defect, 7 = reversable defect"]
                namelist = ["age", "sex", "cpt", "rbp", "chol", "fbsugar", "regc", "maxhr", "exang", "std", "slope",
                            "ves", "thal"]
            elif template == "Cancer Signs":
                formlist = ["Clump Thickness(1-10)", "Uniformity of Cell Size(1-10)", "Uniformity of Cell Shape(1-10)",
                            "Marginal Adhesion(1-10)", "Single Epithelial Cell Size(1-10)", "Bare Nuclei(1-10)",
                            "Bland Chromatin(1-10)", "Normal Nucleoli(1-10)", "Mitoses(1-10)"]
                namelist = ["clump", "cellsize", "cellshape", "marg", "epicell",
                            "bare", "bland", "nucleoli", "mitoses"]



            zipped = zip(formlist, namelist)
            return HttpResponse(render(request, 'ehrs/compcreate.html', {"zipped": zipped}))


def compsuccess(request):
    global template, namelist, formlist, ehruid
    if request.method == 'POST':
        if template == "Vital Signs":
            form = vitalcomp(request.POST)
            if form.is_valid():
                vitaldata = []

                vitaldata.append(form.cleaned_data["age"])
                vitaldata.append(form.cleaned_data["sex"])
                vitaldata.append(form.cleaned_data["cpt"])
                vitaldata.append(form.cleaned_data["rbp"])
                vitaldata.append(form.cleaned_data["chol"])
                vitaldata.append(form.cleaned_data["fbsugar"])
                vitaldata.append(form.cleaned_data["regc"])
                vitaldata.append(form.cleaned_data["maxhr"])
                vitaldata.append(form.cleaned_data["exang"])
                vitaldata.append(form.cleaned_data["std"])
                vitaldata.append(form.cleaned_data["slope"])
                vitaldata.append(form.cleaned_data["ves"])
                vitaldata.append(form.cleaned_data["thal"])

                z = json.load(open("C:\\Users\\DELL\\Desktop\\webclinic\\ehrs\\data.json"))



                composition_uid = ''.join(
                    [random.choice(string.ascii_letters + string.digits) for n in range(20)])
                date_created = str(datetime.datetime.now().strftime("%I:%M%p on %B %d %Y"))

ehrs/templates/ehrs/compcreate.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>Add Composition</title>
    <script src="js/compadd.js"></script>
    <style type="text/css">
        html {
            background-image: url('abc.jpg');
        }

        button.addcomp {
            background-color: #4CAF50;
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
        }

        button.addcomp:hover {
            background: #383;
        }

        a:link {
            color: #93add8;
        }

        a:hover {
            color: red;
        }

        /* selected link */
        a:active {
            color: green;
        }

        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #333;
        }

        li {
            float: left;
        }

        li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        li a:hover {
            background-color: #111;
        }
        input.addehr {
            background-color: #4CAF50;
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
        }

        input.addehr:hover {
            background: #383;
        }

    </style>
</head>
<body background="{% static 'images/abc.jpg' %}">
<ul>
  <li><a href="">Home</a></li>
  <li><a href="">Add EHR</a></li>
  <li><a onclick="">Logout</a></li>
</ul>
<div align="left">
    <h2><u>Enter details for new Composition:</u></h2><br>
    <form method="post" action="{% url 'ehrs:compsuccess' %}">
    {% csrf_token %}
        {% for f, n in zipped %}
            {{ f }}<br>
            <input type="text" name="{{ n }}" id="{{ n }}"><br><br>
        {% endfor %}
        <input type="submit" value="Create Composition." class="addehr">

    </form>
</div>
</body>
</html>

ehrs/templates/ehrs/compdisplay.html
{%  load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>EHR Information</title>
	<script src="js/ehrinfo.js"></script>
	<style type="text/css">

		a { cursor: pointer; }
		a { cursor: pointer; }
	pre.one {
    border-style: solid;
    border-width: 1px;
}
pre.two {
    border-style: solid;
    border-width: 1px;
}

a:link {
    color: #93add8;
}

/* visited link */

/* mouse over link */
a:hover {
    color: red;
}

/* selected link */
a:active {
    color: green;
}
button.addcomp {
    background-color: #4CAF50;
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}

input.addehr {
            background-color: #4CAF50;
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
        }

        input.addehr:hover {
            background: #383;
        }

div {
    box-shadow: 10px 10px 1px #888888;
}
pre {
    border-style: solid;
    border-width: 1px;
}
button.addcomp:hover{
     background: #383;
}

ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover {
    background-color: #111;
}

	</style>

</head>
<body background="{% static 'images/abc.jpg' %}">
<ul>
  <li><a href="">Home</a></li>
  <li><a href="">Add EHR</a></li>
  <li><a onclick="">Logout</a></li>
</ul>

<pre>{{ compdata2 }}</pre>
<br>
<b>Abbreviations For Data</b>
<pre>
    {% for x, y in abbr %}
        {{ x }}: {{ y }}
    {% endfor %}
</pre>
<br>
<b>Predictions for Data:</b><br>
<b>SVM Predictions:</b> <span style="color: blue; ">{{ pred1 }}</span><br>
<b>Neural Network BackPropagation prediction:</b> <span style="color: blue; ">{{ pred2 }}</span><br>
<pre>{{ notation }}</pre>
</body>
</html>

ehrs/templates/ehrs/compsuccess.html
<!DOCTYPE html>
{%  load staticfiles %}
<html>
<head>
	<title>Create New EHR</title>
	<title>Main Page</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

	<style type="text/css">

	input.addehr {
    background-color: #4CAF50;
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}
input.addehr:hover{
     background: #383;
}
a:link {
    color: #93add8;
}
a:hover {
    color: red;
}

/* selected link */
a:active {
    color: green;
}

ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover {
    background-color: #111;
}

</style>
</head>
<body background="{% static 'images/abc.jpg' %}">
<ul>
  <li><a href="">Home</a></li>
  <li><a href="">Add EHR</a></li>
  <li><a onclick="">Logout</a></li>
</ul>
<span style="color: black; ">Composition Created Successfully!</span>
<a href="{% url 'ehrs:main' %}">Go back to Homepage.</a>
</body>
</html>

ehrs/templates/ehrs/createsuccess.html
<!DOCTYPE html>
{%  load staticfiles %}
<html>
<head>
	<title>Create New EHR</title>
	<title>Main Page</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

	<style type="text/css">

	input.addehr {
    background-color: #4CAF50;
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}
input.addehr:hover{
     background: #383;
}
a:link {
    color: #93add8;
}
a:hover {
    color: red;
}

/* selected link */
a:active {
    color: green;
}

ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover {
    background-color: #111;
}

</style>
</head>
<body background="{% static 'images/abc.jpg' %}">
<ul>
  <li><a href="">Home</a></li>
  <li><a href="">Add EHR</a></li>
  <li><a onclick="">Logout</a></li>
</ul>
<span style="color: black; ">EHR Created Successfully!</span>
<a href="{% url 'ehrs:main' %}">Go back to Homepage.</a>
</body>
</html>

ehrs/templates/ehrs/ehrcreate.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>Create New EHR</title>
    <title>Main Page</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <style type="text/css">

        input.addehr {
            background-color: #4CAF50;
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
        }

        input.addehr:hover {
            background: #383;
        }

        a:link {
            color: #93add8;
        }

        a:hover {
            color: red;
        }

        /* selected link */
        a:active {
            color: green;
        }

        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #333;
        }

        li {
            float: left;
        }

        li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        li a:hover {
            background-color: #111;
        }

    </style>
</head>
<body background="{% static 'images/abc.jpg' %}">
<ul>
    <li><a href="">Home</a></li>
    <li><a href="">Add EHR</a></li>
    <li><a onclick="">Logout</a></li>
</ul>
<div align="left">
    <form action="{% url 'ehrs:createsuccess' %}" method="post">
        {% csrf_token %}

        <input type="text" name="ehruid" id="ehruid" placeholder="EHR Uid" >
        <input type="text" name="subuid" id="subuid" placeholder="Subject Uid" required="required">
        <input type="submit" value="Create!" class="addehr"/><br>


    </form>
</div>
</body>
</html>

ehrs/templates/ehrs/ehrinfo.html
{%  load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>EHR Information</title>
	<script src="js/ehrinfo.js"></script>
	<style type="text/css">

		a { cursor: pointer; }
		a { cursor: pointer; }
	pre.one {
    border-style: solid;
    border-width: 1px;
}
pre.two {
    border-style: solid;
    border-width: 1px;
}

a:link {
    color: #93add8;
}

/* visited link */

/* mouse over link */
a:hover {
    color: red;
}

/* selected link */
a:active {
    color: green;
}
button.addcomp {
    background-color: #4CAF50;
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}

input.addehr {
            background-color: #4CAF50;
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
        }

        input.addehr:hover {
            background: #383;
        }

div {
    box-shadow: 10px 10px 1px #888888;
}
pre {
    border-style: solid;
    border-width: 1px;
}
button.addcomp:hover{
     background: #383;
}

ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover {
    background-color: #111;
}

	</style>

</head>
<body background="{% static 'images/abc.jpg' %}">
<ul>
  <li><a href="">Home</a></li>
  <li><a href="">Add EHR</a></li>
  <li><a onclick="">Logout</a></li>
</ul>

<div align="left">
	<h3><u><span style="color: black; ">EHR Information</span></u></h3>
	<font size="4" face="verdana" color="blue"><b><pre id="ehrinfo" class="one">{{ ehrinfo_resp }}</pre></b></font>
	<br><br>
	<h3><u><span style="color: black; ">Compositions for EHR</span></u></h3>
	<span style="font-size: medium; font-family: verdana; color: black; "><pre class="two" id="comp">
        {% for a, x, y in zipped %}
            <a href="{% url 'ehrs:compdisplay' uid a %}">{{ x }}</a>
            {{ y }}
        {% endfor %}
    </pre></span>
	<br><br>
	<h3><u><span style="color: black; ">Create Composition</span></u></h3>
    <form action="{% url 'ehrs:compcreate' %}" method="GET">
        <select name="template">
            <option value="Vital Signs">Vital Signs</option>
            <option value="Cancer Signs">Cancer Signs</option>
        </select><br><br>
        <input type="submit" value="Select Template" class="addehr">
    </form>


</div>
</body>
</html>

ehrs/templates/ehrs/main.html
<!DOCTYPE html>
<html>

{%  load staticfiles %}
<head>
	<title>Main Page</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<style type="text/css">
	html
	{

		background-position:center center;
		background-repeat:no-repeat;
		-webkit-background-size: cover;
		-moz-background-size: cover;
		-o-background-size: cover;
		background-size: cover;

	}
	a { cursor: pointer; }
	pre.one {
    border-style: solid;
    border-width: 1px;
}
pre.two {
    border-style: outset;
    border-width: 1px;
    border-color: #dce2ed;
}
pre.two:hover{
    background-color: #bbbbbb;
}
div {
    box-shadow: 10px 10px 1px #888888;
}
a:link {
    color: #93add8;
}

/* visited link */


/* mouse over link */
a:hover {
    color: red;
}

/* selected link */
a:active {
    color: green;
}
input.addehr {
    background-color: #4CAF50;
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}
input.addehr:hover{
     background: #383;
}


ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover {
    background-color: #111;
}


</style>
</head>
<body background="{% static 'images/abc.jpg' %}">
	<ul>
  <li><a href="">Home</a></li>
  <li><a href="">Add EHR</a></li>
  <li><a onclick="">Logout</a></li>
</ul>

	<div align="left" nbsp>
		<h3><u><font color="black">User Information</font></u></h3>
		<b><span style="font-size: medium; font-family: verdana; color: blue; "><pre class="one" id="userinfo">{{ user_info }}</pre></span></b>
	</div>
	<br><br><br>
	<div align="left">
		<h3><u><font color="black">EHR Details for User</font></u></h3>&nbsp;
        <input class="addehr" type="button" value="Add New" onclick="location.href='{% url 'ehrs:ehrcreate' %}'"  />

		{% for x, y in zipped %}
            <span class="ehrlistblock" style="font-size: medium; font-family: verdana; color: black; ">

                <b><pre class="two" id="ehrlist"><a href="{% url 'ehrs:ehrinfo' x %}">{{ y }}</a> </pre></b>
            </span>

        {% endfor %}
	</div>

</body>
</html>